import json

with open('notebooks/Preprocessing/01_preprocessing.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

for cell in nb['cells']:
    if cell['cell_type'] == 'code':
        src = ''.join(cell['source'])
        if '_cwd = Path.cwd()' in src and 'PROJECT_ROOT' in src:
            cell['source'] = [
                '# Configuration\n',
                '_cwd = Path.cwd()\n',
                'PROJECT_ROOT = None\n',
                'for _p in [_cwd] + list(_cwd.parents):\n',
                '    if (_p / "data" / "features" / "merged_features.csv").exists():\n',
                '        PROJECT_ROOT = _p\n',
                '        break\n',
                'if PROJECT_ROOT is None:\n',
                '    raise FileNotFoundError("Could not locate data/features/merged_features.csv")\n',
                '\n',
                'DATA_RAW = PROJECT_ROOT / "data" / "features"\n',
                'DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"\n',
                'DATA_PROCESSED.mkdir(parents=True, exist_ok=True)\n',
                '\n',
                'MERGED_FILE = DATA_RAW / "merged_features.csv"\n',
                'CLEAN_MASTER_OUT = DATA_PROCESSED / "clean_master_data.csv"\n',
                'NUMERIC_OUT = DATA_PROCESSED / "numeric_features_preprocessed.csv"\n',
                'QUALITY_REPORT_OUT = DATA_PROCESSED / "data_quality_report.csv"\n',
                'SUMMARY_OUT = DATA_PROCESSED / "preprocessing_summary.txt"\n',
                '\n',
                '# --- Column groups (v2 schema: 88 columns) ---\n',
                'METADATA_COLS = ["id", "file_name", "user_no", "question_id", "question"]\n',
                '\n',
                'TARGET_COLS = [\n',
                '    "openness", "conscientiousness", "extraversion", "agreeableness",\n',
                '    "neuroticism", "overall_personality",\n',
                '    "interview_score", "answer_score", "speaking_skills",\n',
                '    "confidence_score", "facial_expression", "overall_performance"\n',
                ']\n',
                '\n',
                '# Audio prosodic (original)\n',
                'AUDIO_COLS = [\n',
                '    "Duration_Sec", "Speech_Rate_WPM", "Mean_Pitch_Hz",\n',
                '    "Mean_Energy", "Mean_ZCR"\n',
                ']\n',
                '\n',
                '# Audio prosodic (new in v2)\n',
                'AUDIO_COLS_NEW = [\n',
                '    "Total_Words", "Articulation_Rate_WPM", "Total_Silence_Sec",\n',
                '    "Silence_Ratio", "Pause_Count", "Avg_Pause_Duration_Sec",\n',
                '    "Std_Pitch_Hz", "Pitch_Range_Hz", "Std_Energy",\n',
                '    "Spectral_Centroid", "Spectral_Rolloff", "Spectral_Contrast",\n',
                '    "Filler_Word_Count", "Filler_Rate_Per_Min"\n',
                ']\n',
                '\n',
                'MFCC_COLS = [f"MFCC_{i}" for i in range(1, 14)]\n',
                '\n',
                'FACE_COLS = [\n',
                '    "face_detected_ratio", "gaze_ratio_mean", "gaze_deviation_mean",\n',
                '    "gaze_stability_std", "smile_score_mean", "smile_score_std",\n',
                '    "frown_score_mean", "frown_score_std", "eye_openness_mean",\n',
                '    "eye_openness_std", "jaw_open_mean", "jaw_open_std",\n',
                '    "brow_raise_mean", "brow_raise_std", "mouth_frown_mean", "mouth_frown_std"\n',
                ']\n',
                '\n',
                'EMOTION_COLS = [\n',
                '    "emotion_happy_mean", "emotion_sad_mean", "emotion_angry_mean",\n',
                '    "emotion_surprise_mean", "emotion_fear_mean", "emotion_disgust_mean",\n',
                '    "emotion_neutral_mean"\n',
                ']\n',
                '\n',
                'POSTURE_COLS = [\n',
                '    "head_centering_score_mean", "absolute_shoulder_slope_mean",\n',
                '    "shoulder_slope_var", "shoulder_width_mean", "shoulder_width_var",\n',
                '    "nose_shoulder_dist_mean", "nose_shoulder_dist_var",\n',
                '    "hand_speed_mean", "hand_to_face_touches", "crossed_arms_score",\n',
                '    "core_speed_mean", "posture_shift_count", "engagement_score", "agitation_score"\n',
                ']\n',
                '\n',
                'TEXT_COLS = ["transcript"]\n',
                '\n',
                'ALL_AUDIO = AUDIO_COLS + AUDIO_COLS_NEW\n',
                'ALL_EXPECTED = (METADATA_COLS + TARGET_COLS + ALL_AUDIO + MFCC_COLS +\n',
                '                FACE_COLS + EMOTION_COLS + POSTURE_COLS + TEXT_COLS)\n',
                '\n',
                'print(f"Project root   : {PROJECT_ROOT}")\n',
                'print(f"Input file     : {MERGED_FILE}")\n',
                'print(f"Output dir     : {DATA_PROCESSED}")\n',
                'print(f"Expected cols  : {len(ALL_EXPECTED)} (from schema)")\n',
                'print(f"Dataset        : 2011 rows x 88 columns (v2)")'
            ]
            break

with open('notebooks/Preprocessing/01_preprocessing.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
print('Fixed configuration cell.')
